// 10W X 18H
export type PlayField = [
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number],
    [number, number, number, number, number, number, number, number, number, number]
];

export const playField: PlayField = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];
